// import './variables/main'
// import './functions/main'
// import './utilityTypes/main'
// import './classes/main'
// import './generics/main'
// import './modules/main'
// import './modules/finance'
// import './typeAliases/main'
import './decorators/main'
